### ISSUE TITLE
new version on hg38

### ISSUE THREAD

**Issue by laurie-tonon** [aeeckhou/shallowHRD#9] opened 2023-02-09 17:01 UTC
Hello,

I would like to run shallowHRD on my samples that were aligned on hg38, but in there is no new script to do so.
Only one script in the old_version folder is base on hg38.
As you say that the new version improved things, would it be possible to have a new version script for hg38?

Thanks a lot

**Comment by aeeckhou** [comment] 2023-02-10 08:44
Hello Laurie, 

Indeed, I would recommend going only through the new version! 

The problem is that I mooved from my lab in which I developped shallowHRD during my PhD. I no longer have access to the large databank of shallow WGS that we had and I wouldn't be confortable releasing a hg38 version online without testing it properly to be honest. 

One solution possible would be to transform your BAM file in fastq again and realigned them on hg19. If it is possible, that would be the most direct solution and probably the best option too. 
I could also send you by mail a theoritical hg38 version before the end of the month but I won't be realeasing it on Github and I cannot guarantee its stability. 

An new **improved** and up to date version of the pipeline is developped and probably finished quite soon in my previous lab. You might want to contact them directly!

Keep me posted,
Alexandre Eeckhoutte

**Comment by laurie-tonon** [comment] 2023-02-10 14:35
Thanks a lot for your answer.
I would be interested if you can send me the theoretical hg38 version. This is just a test, and I just want to validate the shallow WGS sequencing of my samples (I already know the HRD status) and confirm that the complete pipeline can run.
I have a whole cohort of samples that will be run with the new version of the pipeline by your former lab next, but before I just want to see if my sequencing is ok.

I'll send you an email with my details if you want.

**Comment by aeeckhou** [comment] 2023-02-10 15:12
We agreed with the author to the send of a theoritical hg38 new version of the algorithm and we'll continue our exchange directly by mail. I'm therefore closing this issue.

**Closed by aeeckhou** 2023-02-10 15:12 UTC
